---
title: "Determinationskoef-adj"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data model 2:
```{r}
y<-cars$dist
x1<-cars$speed
x2<-x1^2
x3<-x1^3
data<-matrix(c(y,x1,x2,x3),50,4)
colnames(data)<-c("y-værdier","x-værdier","x^2-værdier","x^3-værdier")
print(data)
```

Første søjle i designmatrix:
```{r}
k<-c(rep.int(1,50))
```

Designmatrix og transponeret designmatrix: 
```{r}
X<-matrix(c(k,x1,x2,x3),50,4) 
tX<-t(X)
print(X)
```

Hatmatrix og hatmatrix for nullmodellen beregnes:
```{r}
P1<-X%*%solve(tX%*%X)%*%tX
P0<-k%*%solve(t(k)%*%k)%*%t(k)
```

Devians beregnes:
```{r}
devians0<-t(c(P1%*%y-P0%*%y))%*%c(P1%*%y-P0%*%y)
devians1<-t(c(y-P1%*%y))%*%c(y-P1%*%y)
devians2<-t(c(y-P0%*%y))%*%c(y-P0%*%y) 
```

Determinationskoefficienten og den justerede determinationskoefficient for model 2 beregnes:
```{r}
R2<-round(devians0/devians2,3)
a<-devians1/(50-4)
b<-devians2/(50-1)
c<-a/b
R2adj2<-round(1-c,3)
print(paste("Determinationskoefficienten og den justerede determinationskoefficient er da", R2,"og", R2adj2))
```
