library("pracma")
Sigma=read.table("Sigma.txt")
Sigma=as.matrix(Sigma)
C=read.table("Cny.txt")
C=as.matrix(C)
D=read.table("D.txt")
D=as.matrix(D)
d=read.table("lilled.txt")
d=as.matrix(d)
x=read.table("x.txt")
x=as.matrix(x)
invsqrtSigma=solve(sqrt(Sigma))
dtilde=invsqrtSigma%*%d
Dtilde=invsqrtSigma%*%D
DTD=t(Dtilde)%*%Dtilde
Nulm=matrix(rep(0,676),26,26)
A=matrix(c(rbind(DTD,C),rbind(t(C),Nulm)),63,63)
Beta=solve(A)%*%c(t(Dtilde)%*%dtilde,rep(0,26))
Beta[1:37]