library("pracma")
Sigma=read.table("Sigmany.txt")
Sigma=as.matrix(Sigma)
R=read.table("Cny.txt")
R=as.matrix(R)
X=read.table("D.txt")
X=as.matrix(X)
effekt=read.table("effekt.txt")
effekt=as.matrix(effekt)
y=c(effekt/400,400)
invsqrtSigma=solve(sqrt(Sigma))
ytilde=invsqrtSigma%*%y
Xtilde=invsqrtSigma%*%X
XTX=t(Xtilde)%*%Xtilde
Nulm=matrix(rep(0,676),26,26)
A=matrix(c(rbind(XTX,R),rbind(t(R),Nulm)),63,63)
Ainv=solve(A)
Beta=Ainv%*%c(t(Xtilde)%*%ytilde,rep(0,26))
Beta[1:37]#Her er det første estimat for strømstyrker og spændinger i hele netværket:
for(i in 1:50)
{
  y=c(effekt/c(Beta[21:22],Beta[25],Beta[27],Beta[29],Beta[31],Beta[33],Beta[35:37]),400)
  Sigma=diag((y*0.01)^2)
  invsqrtSigma=solve(sqrt(Sigma))
  ytilde=invsqrtSigma%*%y
  Xtilde=invsqrtSigma%*%X
  XTX=t(Xtilde)%*%Xtilde
  A=matrix(c(rbind(XTX,R),rbind(t(R),Nulm)),63,63)
  Ainv=solve(A)
  Beta=Ainv%*%c(t(Xtilde)%*%ytilde,rep(0,26))
}
y=rnorm(37,mean=Beta[1:37],sd=abs(Beta[1:37])*0.01)
ymf=y
ymf[2]=1
Sigma=diag((y*0.01)^2)
X=diag(1,37)
invsqrtSigma=solve(sqrt(Sigma))
ytildemf=invsqrtSigma%*%ymf
Xtilde=invsqrtSigma%*%X
XTX=t(Xtilde)%*%Xtilde
A=matrix(c(rbind(XTX,R),rbind(t(R),Nulm)),63,63)
Ainv=solve(A)
Beta2=Ainv%*%c(t(Xtilde)%*%ytilde,rep(0,26))
v=c()
P=Xtilde%*%Ainv[1:37,1:37]%*%t(Xtilde)
for(i in 1:length(y))
{
  v=c(v,(ytilde[i]-(P%*%ytilde)[i])/sqrt(1-P[i,i]))
}
v
ymf=y
ymf[2]=1
ytildemf=invsqrtSigma%*%ymf
P=Xtilde%*%Ainv[1:37,1:37]%*%t(Xtilde)
for(i in 1:length(y))
{
  v=c(v,(ytilde[i]-(P%*%ytilde)[i])/sqrt(1-P[i,i]))
}
v